"""add language to posts

Revision ID: 143282383f50
Revises: 2b76c3cf9535
Create Date: 2020-01-24 10:54:33.676075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '143282383f50'
down_revision = '2b76c3cf9535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
